# numpy practice session

## Authored by: Dr. Allah Ditta Babar
## Where to contact:https://github.com/babarkhan786
## Email: adbabar.nibge@gmail.com

In [2]:
# pip instal numpy

In [4]:
# import the library in j.notebook
import numpy as np

# create an array using numpy

In [5]:
np.array(["Pakora", "Samosa", "Raita"])

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [6]:
price = np.array([5, 5, 5])
price

array([5, 5, 5])

In [8]:
type(price)

numpy.ndarray

In [10]:
len(price)

3

In [14]:
food = np.array(["Pakora", "Samosa", "Raita"])

In [16]:
type(food)

numpy.ndarray

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
np.arange(5, 55, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [27]:
np.linspace(1, 10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [31]:
np.ones(50, dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int8)

In [32]:
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [33]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Array Function

In [36]:
a = np.array([10,12,15,2,4,6,100,0.5, 320,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. ,   0.5, 320. ,
        10.3])

In [37]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [38]:
b = np.array([10,3,24,65,3.5,345])
b

array([ 10. ,   3. ,  24. ,  65. ,   3.5, 345. ])

In [39]:
c = np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10. ,   3. ,  24. ,  65. ,   3.5, 345. ])

In [40]:
c.sort()
c

array([  0.5,   2. ,   3. ,   3.5,   4. ,   6. ,  10. ,  10. ,  10.3,
        12. ,  15. ,  24. ,  65. , 100. , 320. , 345. ])

## 2 D array

In [51]:
a = np.array([[1,2,3,4],
              [5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
b = np.array([[6,7, 9, 11],[8,9, 10, 12]])
b

array([[ 6,  7,  9, 11],
       [ 8,  9, 10, 12]])

In [55]:
c = np.concatenate((a,b), axis=0)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 6,  7,  9, 11],
       [ 8,  9, 10, 12]])

In [56]:
c = np.concatenate((a,b), axis=1)
c

array([[ 1,  2,  3,  4,  6,  7,  9, 11],
       [ 5,  6,  7,  8,  8,  9, 10, 12]])

In [61]:
import numpy as np

a = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(a)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [62]:
#  to find the number of dimensions
a.ndim

3

In [65]:
b = np.array([[5,6,7],
             [8,9,10],
              [11,13,13]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 13, 13]])

In [66]:
b.ndim

2

In [67]:
a.size

24

In [68]:
a.shape

(3, 2, 4)

In [78]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
b = a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
np.reshape(a, (1, 9), order='C')

print(a)

[0 1 2 3 4 5 6 7 8]


In [87]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
a.shape

(9,)

In [89]:
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [91]:
b.shape

(1, 9)

In [90]:
c = a[: ,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [92]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [93]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [94]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [96]:
a.sum()

np.int32(45)

In [98]:
a.mean()

np.float64(5.0)

In [102]:
a.max()

np.int32(9)